# Generated by Django 5.0 on 2026-09-23 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_skill_jobposting_latitude_jobposting_location_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobposting',
            name='company_name',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
