# Generated by Django 5.0 on 2026-09-25 05:55

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0004_jobapplication'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplication',
            name='status_changed_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='status',
            field=models.CharField(choices=[('submitted', 'Submitted'), ('reviewing', 'Reviewing'), ('shortlisted', 'Shortlisted'), ('tech_interview', 'Technical round'), ('behavioral_interview', 'Behavioral round'), ('offer', 'Offer extended'), ('hired', 'Hired'), ('not_selected', 'Not selected')], default='submitted', max_length=20),
        ),
    ]
